name: CI

on:
  push:
    branches:
      - dev
    paths:
      - "FicsItCam.uplugin"
      - "Content/**"
      - "Source/**"
      - "ThirdParty/**"
  workflow_dispatch:
  workflow_call:
    secrets:
      WWISE_EMAIL:
        required: true
      WWISE_PASSWORD:
        required: true
      GH_TOKEN:
        required: false

jobs:
  build:
    runs-on: windows-selfhost
    steps:
      - name: Pre Cleanup
        run: Remove-Item ${{ github.workspace }}\* -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - uses: actions/checkout@v4
        with:
          repository: satisfactorymodding/SatisfactoryModLoader
          ref: d1b4dc0b85236e8a68b934f8dacdafa65fa8af2f
          path: SatisfactoryModLoader

      - uses: actions/checkout@v4
        with:
          path: SatisfactoryModLoader/Mods/FicsItCam

      - name: Create UE directory
        run: mkdir ue

      - name: Download, Extract and Setup UE
        working-directory: ue
        run: |
          gh release download --repo satisfactorymodding/UnrealEngine -p "UnrealEngine-CSS-Editor-Win64.7z.*" 5.3.2-css-68
          7z x UnrealEngine-CSS-Editor-Win64.7z.001
          rm UnrealEngine-CSS-Editor-Win64.7z*
          .\\SetupScripts\\Register.bat
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Add Wwise
        run: |
           7z x -aoa C:\\CI\\Wwise.7z -o'${{ github.workspace }}\SatisfactoryModLoader\Plugins\'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WWISE_EMAIL: ${{ secrets.WWISE_EMAIL }}
          WWISE_PASSWORD: ${{ secrets.WWISE_PASSWORD }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build for Development Editor
        run: ${{ github.workspace }}\\ue\\Engine\\Build\\BatchFiles\\Build.bat FactoryEditor Win64 Development -project='${{ github.workspace }}\SatisfactoryModLoader\FactoryGame.uproject'

      - name: Build for Shipping/Client EGS
        run: ${{ github.workspace }}\\ue\\Engine\\Build\\BatchFiles\\Build.bat FactoryGameEGS Win64 Shipping -project='${{ github.workspace }}\SatisfactoryModLoader\FactoryGame.uproject'
      - name: Build for Shipping/Client Steam
        run: ${{ github.workspace }}\\ue\\Engine\\Build\\BatchFiles\\Build.bat FactoryGameSteam Win64 Shipping -project='${{ github.workspace }}\SatisfactoryModLoader\FactoryGame.uproject'


      - name: Package FicsItCam Mod
        run: ${{ github.workspace }}\ue\Engine\Build\BatchFiles\RunUAT.bat -ScriptsForProject='${{ github.workspace }}\SatisfactoryModLoader\FactoryGame.uproject' PackagePlugin -project='${{ github.workspace }}\SatisfactoryModLoader\FactoryGame.uproject' -DLCName='FicsItCam' -build -server -clientconfig=Shipping -serverconfig=Shipping -platform=Win64 -nocompileeditor -installed -merge -utf8output

      - name: Upload FicsItCam-Merged
        id: upload-win64-merged
        uses: actions/upload-artifact@v4
        with:
          name: FicsItCam-Merged
          path: ${{github.workspace}}\SatisfactoryModLoader\Saved\ArchivedPlugins\FicsItCam\FicsItCam.zip
      - name: Upload FicsItCam
        id: upload-win64
        uses: actions/upload-artifact@v4
        with:
          name: FicsItCam
          path: ${{github.workspace}}\SatisfactoryModLoader\Saved\ArchivedPlugins\FicsItCam\FicsItCam-*.zip

      - name: Discord Webhook Action
        uses: Panakotta00/discord-build-status-with-artifact@v0.0.4
        if: always()
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          artifact-url: "${{ steps.upload-win64.outputs.artifact-url }}"
          artifact-name: 'FicsItCam.zip'
          
      - name: Post Cleanup
        if: ${{ !failure() }}
        run: Remove-Item ${{ github.workspace }}\* -Recurse -Force -Confirm:$false -ErrorAction Ignore
